// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "43af2c46-36af-4961-89ac-0fc0f059d339";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onCloseMoreChange();
void onLeavesOpenChange();
void onOpenMoreChange();
void onTalkingChange();

bool closeMore;
bool leavesOpen;
bool openMore;
bool talking;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(closeMore, READWRITE, ON_CHANGE, onCloseMoreChange);
  ArduinoCloud.addProperty(leavesOpen, READWRITE, ON_CHANGE, onLeavesOpenChange);
  ArduinoCloud.addProperty(openMore, READWRITE, ON_CHANGE, onOpenMoreChange);
  ArduinoCloud.addProperty(talking, READWRITE, ON_CHANGE, onTalkingChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
